name: Fix Gradlew Path

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          repository: nhatanhd50-eng/Duix-Mobile
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK (Fixed Directory)
        working-directory: ./duix-android  # CHỈN THAY CHẠY SAI BẤM `duix-android` VÌI BẤC CÔNG DƯỜG `dh_aigc_android`
        run: |
          ./gradlew assembleDebug --stacktrace
